### PR TITLE
Fix Dataset and File Version Summaries 

### LINKED ISSUE #879: Fix: Dataset and File Version Summaries
Since we had an API Refactoring and enhancement from Dataverse API https://github.com/IQSS/dataverse/pull/11859, we need to update Dataset and File Version Summaries first. 

Dataset Page:
- [x] Dataset comparison summary t should be Access: Restricted
Image

- [x] Deaccessioned Font should not be bold
- [x] for the next version of a deaccessioned version, we still should have `View Details` button
Image
Show view details only if:
  1. Current version is NOT deaccessioned
  2. There is a previous non-deaccessioned version to compare with
  3. Current version has a non-string summary (has actual changes)
       
File Page
- [x] If file not included, show text`File not included in this version`
- [x] remove link to dataset version 
Image

### PR DESCRIPTION
**Pull request by ChengShi-1**
## What this PR does / why we need it:
Dataset Page:
- Dataset comparison summary t should be Access: Restricted
- Deaccessioned reason font should not be bold
- for the next version of a deaccessioned version, we still should have View Details button
- Show View Details button if: 1. Current version is not deaccessioned 2. There is a previous non-deaccessioned version to compare with 3. Current version has a non-string summary (has actual changes)

File Page
- If file not included, show text "File not included in this version"
- remove link to dataset version if File not included in this version or deaccessioned without edit access

## Which issue(s) this PR closes:

- Closes #879 

## Suggestions on how to test this:
Some screenshots of the issues are https://github.com/IQSS/dataverse-frontend/issues/879 here.
Comparing to JSF, see if the issues are solved

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
no

## Is there a release notes or changelog update needed for this change?:
yes

### CODE REVIEW

File: src/sections/dataset/dataset-versions/DatasetVersions.tsx [hunk 1]
```diff
@@ -111,36 +111,32 @@ export function DatasetVersions({
           </thead>
           <tbody>
             {datasetVersionSummaries?.map((dataset, index) => {
-              const previousVersion =
-                index < datasetVersionSummaries.length - 1
-                  ? datasetVersionSummaries[index + 1]
-                  : null
+              const isVersionDeaccessioned = (version: DatasetVersionSummaryInfo) =>
```
Comment (ekraffmiller) [inline src/sections/dataset/dataset-versions/DatasetVersions.tsx]: This logic for defining isDeaccessioned is also used in defining selectableVersions, can it be replaced with a function that is called in both places?

File: src/sections/dataset/dataset-versions/DatasetVersions.tsx [hunk 2]
```diff
@@ -173,7 +169,7 @@ export function DatasetVersions({
                   <td>
                     <p style={{ display: 'flex', flexWrap: 'wrap', margin: 0, textAlign: 'left' }}>
                       <SummaryDescription summary={dataset.summary} />
-                      {showViewDetails && (
+                      {showViewDetails && previousVersion && (
```
Comment (ekraffmiller) [inline src/sections/dataset/dataset-versions/DatasetVersions.tsx]: the logic` && previousVersion` seems to be redundant, it's already checked in the definition of showViewDetails in line 139

File: src/sections/file/file-version/FileVersions.tsx
Comment (ekraffmiller) [inline src/sections/file/file-version/FileVersions.tsx:1]: I'm seeing a difference in the File Versions table between the JSF and SPA. 
If a previous version, which didn't include the file, was deaccessioned, than in JSF is shows the Deacessioned reason, but in SPA it shows 'File not included in this version'

Image

Image

**Review by ekraffmiller — COMMENTED** [review]
looks good, just a few comments 👍

File: src/sections/file/file-version/FileVersions.tsx
Comment (ChengShi-1) [reply src/sections/file/file-version/FileVersions.tsx:1]: The "File not included" logic(it's a if-else statement) runs first, so deaccessioned  is ignored. I changed the order of the statements, deaccessioned reason should be good to show now. 
image

**Comment by ChengShi-1** [comment]
Hi @ekraffmiller , thanks for your review! I just fixed them in my new commits.

**Review by ekraffmiller — APPROVED** [review]
looks good, approved!

**Comment by ekraffmiller** [comment]
I found a discrepancy between JSF and SPA for Draft versions, after deaccessioning.  (The text shown in the SPA should only be shown for published versions )
SPA:
Screenshot 2025-11-10 at 3 53 18 PM
JSF:
Screenshot 2025-11-10 at 3 54 03 PM

**Comment by ekraffmiller** [comment]
If there are no details between versions, the "View Details" link appears, but when you click on it, there are no differences.  For example, in this dataset, created multiple versions with no changes.  
Screenshot 2025-11-10 at 4 06 53 PM
Screenshot 2025-11-10 at 4 07 01 PM

This is the same behavior as the JSF, but I think it could be more user friendly to show a message saying there are no differences, rather than a link to View Details.

**Comment by ChengShi-1** [comment]
@ekraffmiller Thanks for catching them. I solved these two
- Remove View Detail button - the backend will still return an object, and some fields are undefined, so I added an additional check for it here [useGetDatasetVersionDiff.ts](https://github.com/IQSS/dataverse-frontend/blob/3feee867f4669fcd06f8b1786bd2ff263e66d7b8/src/sections/dataset/dataset-versions/view-difference/useGetDatasetVersionDiff.ts#L47C5-L56C63)
image

- 

image

**Comment by ekraffmiller** [comment]
looks good! merging
