### PR TITLE
Fix/454 dataset page actions for draft

### LINKED ISSUE #454: Dataset Page Actions not working for draft versions
Since the default dataset version has changed from :latest to :latest-published, more links need to updated to include` &version=DRAFT `when working with a draft version.  The "Access Dataset", "Edit Metadata" and "FIle Upload" actions need to be updated to navigate to the correct dataset url.

### PR DESCRIPTION
**Pull request by g-saracca**
**What this PR does / why we need it**:

> Since the default dataset version has changed from :latest to :latest-published, more links need to updated to include&version=DRAFTwhen working with a draft version. The "Access Dataset", "Edit Metadata" and "FIle Upload" actions need to be updated to navigate to the correct dataset url.

**Which issue(s) this PR closes**:

Closes #454 

**Special notes for your reviewer**:
There is also a fix for duplicate react keys on collection page dataset cards.

**Suggestions on how to test this**:

- Create a Dataset, go to that Dataset and click the Edit Dataset => Files (Upload) should navigate correctly to the File Upload page. (`version=DRAFT` query param should be present on the URL)
- Create a Dataset, go to that Dataset and click the Edit Dataset => Metadata should navigate correctly to the Edit dataset metadata page. (`version=DRAFT` query param should be present on the URL)
- Publish that Dataset and navigate to the Files Upload  & the Edit Dataset page. (`version=DRAFT` query param should NOT be present on the URL)
- Access Dataset dropdown should not be visible when the Dataset has no files. Try uploading some files from the JSF version and check that in the Dataset View page on the SPA now the Access Dataset dropdown is visible and works correctly.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No

**Is there a release notes update needed for this change?**:
No

**Additional documentation**:
No

### CODE REVIEW

File: src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function DatasetUploadFilesButton() {
   }
 
   const handleClick = () => {
-    navigate(`${Route.UPLOAD_DATASET_FILES}?persistentId=${dataset.persistentId}`)
+    navigate(`${Route.UPLOAD_DATASET_FILES}?${QueryParamKey.PERSISTENT_ID}=${dataset.persistentId}`)
   }
```
Comment (ekraffmiller) [inline src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.tsx:22]: I think the handleClick() function also needs logic to add version=DRAFT, similar to EditDatasetMenu component.  When I click on the button in a draft dataset, I get "Page Not Found".

**Review by ekraffmiller — CHANGES_REQUESTED** [review]
Looks good! I just found one place where I think we need to add the version=DRAFT logic.

File: src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.tsx (hunk 1 above)
Comment (g-saracca) [reply src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.tsx:33]: Nice catch! I forgot about that button down there, thanks! I've fixed it.

**Review by ekraffmiller — APPROVED** [review]
Looks good!

**Review by GPortas — APPROVED** [review]
I have tested all scenarios and it works good!
