### PR TITLE
Fix Incorrect Filter Query for facet values that contain ":"

### LINKED ISSUE #812: Incorrect Filter Query for facet values that contain ":"
**What steps does it take to reproduce the issue?**
In the SPA, create dataset, then upload a file in it. Then edit that file tags adding a custom one like "John: Doe" (needs to contain a ":" in it).
Then navigate to the collection page and select the "John: Doe" facet under File Tag heading.
The facet should be applied incorrectly like fileTag: "John" and not fileTag: "John: Doe", which will lead into incorrect search results.

- When does this issue occur?
When we have facet values that contain a colon in it.

- Which page(s) does it occur on?
Collection Page.

- What happens?
Incorrect facet filtering.

- To whom does it occur (all users, curators, superusers)?
All users

- What did you expect to happen?
Facet filter query to be applied correctly.

**Which version of Dataverse Frontend are you using?**
Latest from develop.

### PR DESCRIPTION
**Pull request by g-saracca**
## What this PR does / why we need it:
See original issue description.

## Which issue(s) this PR closes:

- Closes #812 

## Suggestions on how to test this:
See original issue.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No, but this is a screenshot of a Facet Filter Query that contains ":" in it's value.
Screenshot 2025-08-21 at 16 19 56

## Is there a release notes update needed for this change?:
No

## Additional documentation:
N/A

### CODE REVIEW

File: src/sections/collection/CollectionHelper.ts [hunk 1]
```diff
@@ -46,6 +60,33 @@ export class CollectionHelper {
...
+    filterQueryKey: string
+    filterQueryValue: string
+  } | null {
+    const idx = filterQuery.indexOf(':')
+    // If idx === -1 there is no colon at all, invalid.
+    // If idx === 0 colon is the first character, means the key is empty (":value"), invalid.
+    // If idx === filterQuery.length - 1 colon is the last character, means the value is empty ("key:"), invalid.
+    if (idx <= 0 || idx === filterQuery.length - 1) return null
+
+    const filterQueryKey = filterQuery.slice(0, idx).trim()
```
Comment (ChengShi-1) [inline src/sections/collection/CollectionHelper.ts:77]: the `trim()` trims whitespace here, so if there is a tag with leading/trailing whitespace, it will be trimmed. I test with JSF and notice the whitespaces are not trimmed in the query

**Review by ChengShi-1 — COMMENTED** [review]
Hi German, good fix! one comment about the whitespace

**Review by ChengShi-1 — APPROVED** [review]
Looks good to me

**Comment by ChengShi-1** [comment]
@ofahimIQSS Hi Omer, sorry, I moved it to ready for QA but this one is waiting for more discussion, not ready for QA now.

**Comment by g-saracca** [comment]
> @ofahimIQSS Hi Omer, sorry, I moved it to ready for QA but this one is waiting for more discussion, not ready for QA now.

@ChengShi-1 oh no please move forward with this. I'll create a follow up issue in the dataverse repo.

**Comment by ChengShi-1** [comment]
@g-saracca lol, I misunderstood what you said in the standup meeting.
@ofahimIQSS I re-assigned Omer here, thanks!

**Comment by ofahimIQSS** [comment]
image
image

fix looks good, merging
