### PR TITLE
Dataset page: Fix 404 error viewing dataset for deaccessioned version

### LINKED ISSUE #673: Dataset Page: 404 error viewing Dataset if there is a deaccessioned version
**What steps does it take to reproduce the issue?**

1. Publish a dataset,
2. Create a second version of the dataset and publish it 
3. Deaccession the second version of the dataset
4.  Logout
5.  Go to the Root collection page
6. The Published version of the dataset should be visible, click on that
7. 404 Error

- Which page(s) does it occur on?
Dataset Page

- What happens?
404 Error
The API call generating the error is
http://localhost:8000/api/v1/datasets/:persistentId/versions/:latest-published/downloadsize?persistentId=doi:10.5072/FK2/IOFMXO&includeDeaccessioned=true&mode=Original
Error Message:
{"status":"ERROR","message":"Dataset version :latest-published of dataset 4 not found"}

- To whom does it occur (all users, curators, superusers)?
users who are not logged in

- What did you expect to happen?
It should show the published version of the Dataset

**Which version of Dataverse Frontend are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

- https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

### PR DESCRIPTION
**Pull request by ChengShi-1**
## What this PR does / why we need it:

users who are not logged in

- Publish a dataset,
- Create a second version of the dataset and publish it
- Deaccession the second version of the dataset
- Logout
- Go to the Root collection page
- The Published version of the dataset should be visible, click on that:  404 Error

Which page(s) does it occur on?
Dataset Page

What happens?
404 Error

The API call generating the error is:
`http://localhost:8000/api/v1/datasets/:persistentId/versions/:latest-published/downloadsize?persistentId=doi:10.5072/FK2/IOFMXO&includeDeaccessioned=true&mode=Original`

Error Message:
{"status":"ERROR","message":"Dataset version :latest-published of dataset 4 not found"}

## Which issue(s) this PR closes:

- Closes #673

## Special notes for your reviewer:

- The error happens because we set parameter `includeDeaccessioned == True` in some API,`/downloadsize`, which will return an 404 Error. Reference of the includeDeaccessioned's description in [Native API doc](https://guides.dataverse.org/en/latest/api/native-api.html#:~:text=By%20default%2C%20deaccessioned%20dataset%20versions%20are%20not%20supported,must%20specify%20this%20through%20the%20includeDeaccessioned%20query%20parameter.)

- Other behaviors on Dataset Versions tab:
- If the user is authenticated, disable the links to navigate to deaccessioned version in `dataset version` columns.
- Always disable the link to navigate to current dataset version (It's not happened in JSF Dataset Version, but in File Version tab, I think it's good to add it for keeping a consistency)
- Logic added on checkbox(related to compare two versions), and `View Details` because we have to check if the deaccessioned version is included the comparison, if there is a deaccessioned version, we have to disallow the comparison for prevent an error from api.
- changes on `it('renders the Dataset Files tab',` because there was two same tests for `Terms` and no test for `Files`.

Other bug didn't solve, waiting for an issue in backend.
If there is an deaccessioned dataset version with a file, the file always show Deaccessioned version file page. However, the api end point will return 404 error `message: File metadata for file with id 3 in dataset version 3.0 not found` 

## Suggestions on how to test this:
Other bug didn't solve, waiting for an issue to be solved.
If there is an deaccessioned dataset version with a file, the `File` tab and the file page always show Deaccessioned version file page. However, the api end point will return 404 error `message: File metadata for file with id 3 in dataset version 3.0 not found` which lead an error in the tab and file page.

Test on Deaccessioned dataset
1. Create a collection 
2. create a dataset
3. Publish it
4. Deaccession the dataset

Test it two rounds (1) log in as an authenticated user, (2) don't log in, or as an unauthenticated user
(1) authenticated user
1. If you're an authenticated user, the deaccessioned dataset should have four tabs
2. Navigate to the `Versions` tab, the other versions of deaccessioned dataset are clickable

(2) unauthenticated user
1. If you're an authenticated user, the deaccessioned dataset should just have one tab
2.Navigate to the `Versions` tab, the other versions of deaccessioned dataset are not clickable
image

Also, we have changes on breadcrumb navigation behavior, so please test it as well. 
1. create a dataset(test it on draft and released version)
2. then go to file uploader/edit metadata page
3. click the breadcrumb of the dataset, check if it navigates to latest accessible(which is latest non-deaccessioned) dataset version

### CODE REVIEW

**Comment by ChengShi-1** [comment]
Hi @g-saracca , it's ready for review again, thanks! 
I applied `includeDeaccessioned` to FilesDownloadSize and FilesCountInfo so it could be affacted by users' permission on `canUpdateDataset`.

**Review by g-saracca — CHANGES_REQUESTED** [review]

File: src/sections/collection/collection-items-panel/items-list/dataset-card/DatasetCardHelper.ts [hunk 1]
```diff
@@ -15,6 +16,13 @@ export class DatasetCardHelper {
       params.version = versionNumber
     }
 
+    if (
+      versionNumber === DatasetNonNumericVersion.DRAFT &&
+      publishingStatus === DatasetPublishingStatus.DEACCESSIONED
+    ) {
+      params.version = DatasetNonNumericVersion.LATEST_PUBLISHED
+    }
```
[the remark this answers is not in the document]
Comment (ChengShi-1) [reply src/sections/collection/collection-items-panel/items-list/dataset-card/DatasetCardHelper.ts:24]: Yes right, it will re-direct to `:draft`

File: tests/component/dataset/domain/models/DatasetMother.ts [hunk 2]
```diff
@@ -47,7 +47,7 @@ export class DatasetVersionMother {
   static createDeaccessioned(props?: Partial<DatasetVersion>): DatasetVersion {
     return this.create({
       publishingStatus: DatasetPublishingStatus.DEACCESSIONED,
-      isLatest: false,
+      isLatest: faker.datatype.boolean(),
```
Comment (g-saracca) [inline tests/component/dataset/domain/models/DatasetMother.ts:50]: Can we avoid this `faker.datatype.boolean()` ?, the result of this could be `true` or `false` randomly rifht? and if this is then used in a storybook or in a test it could throw different results.
For Stories this could change how stories look and show unwanted changes to reiew.

File: tests/component/sections/dataset/Dataset.spec.tsx [hunk 3]
```diff
@@ -282,8 +282,8 @@ describe('Dataset', () => {
     cy.findByRole('columnheader', { name: '1 to 10 of 200 Files' }).should('exist')
   })
 
-  it('should only render Versions tab if the dataset is in deaccessioned version, and user is not allowed to update', () => {
-    const testDataset = DatasetMother.createDeaccessioned()
+  it('should only render Versions tab if the dataset is in deaccessioned version, and user user has noedit permission', () => {
```
Comment (g-saracca) [inline tests/component/sections/dataset/Dataset.spec.tsx]: user has no edit permission - typo

File: tests/component/sections/dataset/dataset-files/DatasetFilesScrollable.spec.tsx [hunk 4]
```diff
@@ -96,6 +96,21 @@ describe('DatasetFilesScrollable', () => {
...
+        datasetVersion={datasetVersion}
+        canUpdateDataset={false}
+      />
+    )
+
+    cy.wait(1000)
+    cy.findByRole('table').should('exist')
+    cy.findByRole('columnheader', { name: /Files/ }).should('exist')
+  })
+
```
Comment (g-saracca) [inline tests/component/sections/dataset/dataset-files/DatasetFilesScrollable.spec.tsx:113]: Isn't the files list render anyways? maybe the test naming isn't correct?

File: tests/component/sections/dataset/dataset-terms/DatasetTerms.spec.tsx [hunk 5]
```diff
@@ -68,6 +68,21 @@ describe('DatasetTerms', () => {
...
+        filesRepository={fileRepository}
+        datasetPersistentId={datasetPersistentId}
+        datasetVersion={datasetVersion}
+        canUpdateDataset={false}
+      />
+    )
+    cy.findByText('Dataset Terms').should('exist')
+    cy.findByText('Restricted Files + Terms of Access').should('exist')
+  })
+
```
Comment (g-saracca) [inline tests/component/sections/dataset/dataset-terms/DatasetTerms.spec.tsx:85]: Same here, I don't understand the naming of this test

**Review by g-saracca — APPROVED** [review]
