### PR TITLE
Fix UploadDatasetFiles Component test

### LINKED ISSUE #481: Race Condition in UploadDatasetFiles unit test
There seems to be a race condition in the component test, UploadDatasetFiles.spec.tsx. 
The error happens in 'restrict uploaded file' test:
https://github.com/IQSS/dataverse-frontend/actions/runs/10743959041/job/29799827812.

Screenshot 2024-09-06 at 4 23 28 PM
This error only happens intermittently and the test was successful on the second attempt.

### PR DESCRIPTION
**Pull request by ekraffmiller**
## What this PR does / why we need it:
Updates UploadDatasetFiles.spec.tsx to avoid race condition errors.

## Which issue(s) this PR closes:

- Closes #481 

## Special notes for your reviewer:
I wasn't able to consistently produce this error, so it's hard to tell if this will definitively fix the bug. But there were multiple places where the test referred to a checkbox by the order on the page, not by an id, which could produce problems since the RestrictedModal and the UploadedFiles component both contain multiple checkboxes.
I added a test that the RestrictedModel is closed, and I added testids to multiple elements to make sure the correct checkboxes are being tested.

## Suggestions on how to test this:
Review the code, run locally and check the Github actions.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

File: src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx [hunk 1]
```diff
@@ -153,6 +153,7 @@ export function UploadedFiles({
                       <div>
                         <Form.Group.Checkbox
                           label={t('restricted')}
+                          data-testid={'restricted_checkbox_' + file.fileName}
```
Comment (g-saracca) [inline src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx:156]: Is there the possibility that could be multiple files with same fileName?
If so but that is not going to be the case for the tests thats ok, if not maybe we should use something else?

**Review by g-saracca — COMMENTED** [review]
Looks good, just one question.

File: src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx (hunk 1 above)
Comment (ekraffmiller) [reply src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx:156]: If that happens, the form should rename the second uploaded file, for example in JSF:
Screenshot 2025-01-14 at 1 28 08 PM

But that I tried doing that in the SPA and the second upload of the file fails silently, rather than renaming. I will create an issue for that.

Comment (g-saracca) [reply src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx:156]: ok so for testing purposes I think its ok to use the fileName right?

Comment (ekraffmiller) [reply src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx:156]: Yes I think so 👍

**Review by g-saracca — APPROVED** [review]

**Comment by ofahimIQSS** [comment]
Tests are passing, merging PR
